### ISSUE TITLE
sesam client v0.0.23 error

### ISSUE THREAD

**Issue by ga-hegsvold** [sesam-io/sesam#16]
$ cd sesam-home/sesam-node-railml-remodelling && ../../sesam -version && ../../sesam -vv test

sesam version 0.0.23

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/sesam-node-railml-remodelling

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

Checking directory: /home/travis/build/datanav/jernbaneverket-sesam-config/sesam-home/

...

10000 tries before it stops

**Comment by BaardBouvet** [comment]
This is a known bug. Workaround until fixed is to use the 0.0.22 version.

**Comment by BaardBouvet** [comment]
Fixed in PR #19
